#!/usr/bin/env python3
"""Generate the committed cached run by executing a full, real experiment once.

The cached fixture is therefore a *recording of a genuine run* (real OpenAI
dialogue + real judges), not hand-authored data — it is regenerated by this
script and clearly labelled "cached" in the UI. Run from repo root:

    python scripts/generate_fixture.py            # full 6+2 run
    python scripts/generate_fixture.py --quick    # 3+1, fewer turns (dev)
"""
import argparse
import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.harness import run_experiment  # noqa: E402
from app.config import get_settings  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true")
    args = ap.parse_args()

    s = get_settings()
    if not s.live_enabled:
        print("WARNING: no OPENAI_API_KEY — fixture will use the fallback text path.")
    n_skills = 3 if args.quick else 5
    n_turns = 2 if args.quick else 3

    t0 = time.time()
    print(f"Generating cached run (skills={n_skills}, turns={n_turns}, model={s.openai_model})...")
    if args.quick:
        from app.domain.personas import PERSONA_BY_KEY
        trained = [PERSONA_BY_KEY[k] for k in ("guesser", "memorizer", "anxious")]
        held = [PERSONA_BY_KEY["adversarial"]]
    else:
        trained = held = None  # defaults: 6 trained + 2 held

    rep = run_experiment(mode="cached", n_skills=n_skills, n_turns=n_turns,
                         trained=trained, held=held, model=s.openai_model,
                         parallel=True)
    rep["meta"]["generated_seconds"] = round(time.time() - t0, 1)

    out = ROOT / "backend" / "app" / "fixtures" / "cached_run.json"
    out.write_text(json.dumps(rep, indent=2))
    b, i = rep["metrics"]["baseline"], rep["metrics"]["improved"]
    print(f"\nDone in {rep['meta']['generated_seconds']}s -> {out}")
    print(f"  verdict: {rep['verdict']['label']}")
    print(f"  learning_gain  v0={b['learning_gain']}  v1={i['learning_gain']}")
    print(f"  transfer       v0={b['transfer']}  v1={i['transfer']}")
    print(f"  answer-giving  v0={b['answer_giving_rate']}  v1={i['answer_giving_rate']}")
    print(f"  misconception  v0={b['misconception_correction']}  v1={i['misconception_correction']}")


if __name__ == "__main__":
    main()
